const productos = [
  {
    id: 1,
    nombre: "Areca",
    imagen: "img/plantas-interior/areca.webp",
    descripcion:
      "Nativa de húmedos bosques tropicales desde Malasia hasta las Islas Salomón, comúnmente conocida como Palmera Areca. Es de esas plantas resistentes que exigen poca atención, perfecta para principiantes que buscan una compañera de piso fácil de cuidar, aunque precisa de unos cuidados básicos que deberás tener en cuenta.",
    precio: 36.99,
    stock: 20,
    tipo: "interior",
    seleccion: "no",
  },
  {
    id: 2,
    nombre: "Costilla de Adán",
    imagen: "img/plantas-interior/costilla_adan.webp",
    descripcion:
      "La Monstera Deliciosa es perfecta para dar un toque de jungla a tu hogar. ¿Sabías que las hojas cuando son jóvenes suelen ser completas? a medida que la planta va cumpliendo años empieza a desarrollar hojas cada vez más agujereadas.",
    precio: 26.99,
    stock: 1,
    tipo: "interior",
    seleccion: "si",
  },
  {
    id: 3,
    nombre: "Euphorbia Eritrea",
    imagen: "img/plantas-interior/euphorbia-eritrea.webp",
    descripcion:
      "La Euphorbias Eritrea, o Cowboy, es muy fácil de cuidar. De hecho prefiere que la dejen tranquila. Cuanto menos caso le hagas más rápido crecerá.",
    precio: 41.99,
    stock: 5,
    tipo: "interior",
    seleccion: "si",
  },
  {
    id: 4,
    nombre: "Ficus Ginseng Bonsai",
    imagen: "img/plantas-interior/ficus-ginseng.webp",
    descripcion:
      "El Ficus Microcarpa Ginseng tiene apariencia de Bonsai, la forma voluminosas de sus ramas dará a tu hogar un toque especial. Los ficus como el ginseng, empleados para cultivar los Bonsáis, son árboles considerados Bonsáis de interior porque no soportan las heladas.",
    precio: 27.99,
    stock: 12,
    tipo: "interior",
    seleccion: "no",
  },
  {
    id: 5,
    nombre: "Sansevieria Cylindrica Trenzada",
    imagen: "img/plantas-interior/optunia_pallida.webp",
    descripcion:
      "La Sansevieria Cylindrica es una variedad de planta de interior de la familia de las Sansevierias. Perfecta para aportar un toque moderno y escultural a tu decoración. Es una planta muy fácil de cuidar y resistente. Comprar Sansevieria Cylindrica trenzada para decorar tu hogar es siempre un acierto por su bajo mantenimiento y su capacidad para purificar el aire.",
    precio: 26.99,
    stock: 2,
    tipo: "interior",
    seleccion: "no",
  },
  {
    id: 6,
    nombre: "Pachira Aquatica",
    imagen: "img/plantas-interior/pachira_aquatica.webp",
    descripcion:
      'La Pachira, también conocida como "money tree" o "árbol del dinero," es una planta de interior popular debido a su apariencia atractiva y su reputación de traer buena suerte y prosperidad según la tradición del feng shui. Es una planta de interior apta para mascotas y niños pequeños, no es tóxica y además purifica el aire de tu hogar. ',
    precio: 25.99,
    stock: 4,
    tipo: "interior",
    seleccion: "no",
  },
  {
    id: 7,
    nombre: "Sansevieria Cylindrica Trenzada",
    imagen: "img/plantas-interior/sansevieria_cylindrica.webp",
    descripcion:
      "La Sansevieria Cylindrica es una variedad de planta de interior de la familia de las Sansevierias. Perfecta para aportar un toque moderno y escultural a tu decoración. Es una planta muy fácil de cuidar y resistente. Comprar Sansevieria Cylindrica trenzada para decorar tu hogar es siempre un acierto por su bajo mantenimiento y su capacidad para purificar el aire.",
    precio: 34.99,
    stock: 3,
    tipo: "interior",
    seleccion: "no",
  },
  {
    id: 8,
    nombre: "Sansevieria Trifasciata",
    imagen: "img/plantas-interior/sansevieria_laurentii_.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 22.99,
    stock: 17,
    tipo: "interior",
    seleccion: "no",
  },
  {
    id: 9,
    nombre: "Aloe Arborescens",
    imagen: "img/plantas-exterior/Aloe_arborescens.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 29.99,
    stock: 17,
    tipo: "exterior",
    seleccion: "no",
  },
  {
    id: 10,
    nombre: "Piña común",
    imagen: "img/plantas-exterior/Ananas_comosus.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 19.99,
    stock: 17,
    tipo: "exterior",
    seleccion: "si",
  },
  {
    id: 11,
    nombre: "Begonia Rojo",
    imagen: "img/plantas-exterior/Begonia_Hiemalis_roja.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 39.99,
    stock: 17,
    tipo: "exterior",
    seleccion: "no",
  },
  {
    id: 12,
    nombre: "Burganvilla Rosa",
    imagen: "img/plantas-exterior/Bougainvillea_Rosa.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 44.99,
    stock: 7,
    tipo: "exterior",
    seleccion: "si",
  },
  {
    id: 13,
    nombre: "Cipres",
    imagen: "img/plantas-exterior/cipres_cupressus.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 34.99,
    stock: 5,
    tipo: "exterior",
    seleccion: "no",
  },
  {
    id: 14,
    nombre: "Árbol Candelabro",
    imagen: "img/plantas-exterior/Euphorbia_Eritrea.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 25.99,
    stock: 5,
    tipo: "exterior",
    seleccion: "si",
  },
  {
    id: 15,
    nombre: "Coral Cactus",
    imagen: "img/plantas-exterior/Euphorbia_Lactea.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 31.99,
    stock: 2,
    tipo: "exterior",
    seleccion: "no",
  },
  {
    id: 16,
    nombre: "Lavanda Dentada",
    imagen: "img/plantas-exterior/Lavanda_dentata.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 20.99,
    stock: 3,
    tipo: "exterior",
    seleccion: "no",
  },
  {
    id: 17,
    nombre: "Romero",
    imagen: "img/plantas-exterior/romero_rosmarinus.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 15.99,
    stock: 3,
    tipo: "exterior",
    seleccion: "si",
  },
  {
    id: 18,
    nombre: "Ave del paraíso",
    imagen: "img/plantas-exterior/strelitzia_reginae.webp",
    descripcion:
      "De entre sus hermanas, la Sansevieria Trifasciata Laurentii es las más popular, debido a sus hojas moteadas de color verde grisáceo y bordes de color amarillo cremoso.",
    precio: 35.99,
    stock: 2,
    tipo: "exterior",
    seleccion: "si",
  },
];
